spring:
  application:
    name: spring-mvc-assignment1

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true